### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by harveyhu2012** [hackgfw/openwrt-gfw-packages#1]
1.请问这个是防止什么污染的
echo "iptables -I protectdns -m u32 --u32 \"4 & 0x1FFF = 0 && 0 >> 22 & 0x3C @ 8 & 0x8000 = 0x8000 && 0 >> 22 & 0x3C @ 14 = 0\" -j DROP" >> $rulefile.tmp

2.为什么专门建一个protectdns链？看旧版是这样写的
        echo "iptables -I INPUT -p udp --sport 53 -m string --algo bm --hex-string \"|$hexip|\" --from 60 --to 180  -j DROP" >> $RULEFILENAME.tmp 
        echo "iptables -I FORWARD -p udp --sport 53 -m string --algo bm --hex-string \"|$hexip|\" --from 60 --to 180 -j DROP" >> $RULEFILENAME.tmp
建一个protectdns的目的是为了跳过loop(! -i lo)吗？

3.有的版本用iptables -t mangle -I PREROUTING，有什么区别？

**Comment by hackgfw** [comment]
**问题1**  对应的是 AntiDNSPoisoning 中提到的 "GFW除了会返回被污染的IP同时，还有可能返回不包含任何查询结果的应答,Answer RRs 和 Authority RRs 均为0. 这个正常情况是不会出现的。即使查询完全不存在的域名，其应答也会包含根服务器的Authority记录"  

**问题2** 建立protectdns是出于性能考虑，否则对于非dns流量依然要把所有防污染规则过一遍。至于“! -i lo”这个和问题1有关，实际上 dnsmasq也会返回Answer RRs 和 Authority RRs 均为0的应答。  

按照DNS规范，查询不存在的域名应该返回NXDOMAIN，并需要注明权威服务器，例如
- 查询不存在的顶级域名 non.exist.domain 所返回的NXDOMAIN应答中应包含 a.root-servers.net 根服务器的权威应答
- 查询不存在的 .com 域名 nonexistdomain.com 所返回的NXDOMAIN应答中应包含 a.gtld-servers.net com服务器的权威应答
- 查询不存在的微软域名 nonexistdomain.microsoft.com 所返回的NXDOMAIN应答中应包含 ns1.msft.net 微软服务器的权威应答  

但是如果运营商的DNS对于不存在的域名返回了一个广告IP地址，这时dnsmasq虽然知道该域名不存在（通过 bogusnxdomain 选项设置），但是没有办法确定权威服务器是哪个，因此dnsmasq无法发出一个符合规范的NXDOMAIN的应答给局域网里的客户端，结果就是dnsmasq会发送一个Answer RRs 和 Authority RRs 均为0的NXDOMAIN应答。  
通常情况下不会遇到什么问题，因为如果是局域网的客户向路由器发起DNS查询，dnsmasq的应答是走防火墙OUTPUT链，而DNS防污染是写在INPUT和FORWARD链上的，不会把dnsmasq的应答干掉。但是有个例外就是如果登录路由器的SSH，在路由器上查询域名，这个时候dnsmasq的应答会先过防火墙OUTPUT链再通过INPUT链到达路由器自己，导致其应答被干掉，因此才加了 “! -i lo”将环回过滤掉。  
这个问题旧版不存在，因为旧版的脚本会把运营商返回的广告IP应答包直接丢掉，最终dnsmasq会从国外的dns服务器获得一个符合规范的NXDOMAIN应答，并将其转发给客户端。  

**问题3** 最早的脚本使用 mangle 表来过滤规则是因为当时的 openwrt 防火墙在重启后（/etc/init.d/firewall restart）不会清空 mangle 表，使用 mangle 表可以省去处理防火墙重启的代码。不过后来版本的 openwrt 防火墙重启时也会清空 mangle 表，因此最终我还是把处理防火墙重启的代码加上了，同时因为 mangle 表有的版本 openwrt 会清，有的不会，判断起来太麻烦，而 filter 表不管什么版本的 openwrt 都会清，所以将规则移到了 filter 表。

**Comment by harveyhu2012** [comment]
非常感谢！回答的非常详尽，明白了。
